version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - ./docker/stirling/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./docker/stirling/extraConfigs:/configs
      - ./docker/stirling/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
